### PR TITLE
Flipped the Function and Pins 

### PR DESCRIPTION
**Pull request by wel97459**
It seemed that the Pin should be the FPGA pin names and not the function of what they are connected too.
To make it even more confusing, there was some of the lists that had the functions as the FPGA pin names.

### CODE REVIEW

**Comment by wuxx** [comment]
Hello, yes, it was my oversight, but I think it might be better to refer to the modification here
https://github.com/q3k/chubby75/blob/master/5a-75b/hardware_V7.0.md

**Comment by wel97459** [comment]
is still worth fixing this in your repo as it's link to by all the sellers in China.

**Comment by wel97459** [comment]
bump!

**Comment by wuxx** [comment]
Okay, I'm sorry for the late reply. It's already merged

**Pull request merged**
